/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import huellitas.*;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Alumno
 */
public class jifAgregarAdopcion extends javax.swing.JInternalFrame {
    private Validaciones validar = new Validaciones();  
    private Adopcion adoptar = new Adopcion();
    private Animal animal = new Animal();
    private AlbergueTemporal temporal = new AlbergueTemporal();
    
    private jifInformacionAn info;
    private jifVerImagen verFoto;
        
    private JFileChooser selector = new JFileChooser();
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes", "jpg","jpeg","png");
    private String rutaCredencial;
    private String rutaComprobante;
    
    private ResultSet rs;
    private int id;
    private Image foto;
    private String localizacion;
    private String tipoCe;
    private String tipoCo;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Image getFoto() {
        return foto;
    }

    public void setFoto(Image foto) {
        this.foto = foto;
    }
    
    public String getLocalizacion() {
        return localizacion;
    }

    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }
        
    /**
     * Creates new form jifAdoptar
     */
    public jifAgregarAdopcion(int id, String localizacion) {
        this.id = id;
        this.localizacion = localizacion;
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnInfoAnimal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnCredencial = new javax.swing.JButton();
        btnComprobante = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        txtTelefonoR = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOcupacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTFFijo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreR = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel16.setText("jLabel16");

        setClosable(true);
        setResizable(true);
        setTitle("Adopción - Agregar");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Huellita.png"))); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        lblFoto.setToolTipText("Ver imágen");
        lblFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFotoMouseClicked(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre del animal:");

        btnInfoAnimal.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        btnInfoAnimal.setText("Ver información del animal");
        btnInfoAnimal.setToolTipText("Ver la información completa del animal adoptado");
        btnInfoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoAnimalActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Amatic SC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Adoptar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Credencial");

        jLabel17.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Comprobante de domicilio");

        btnCredencial.setToolTipText("Subir la credencial del adoptante");
        btnCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCredencialActionPerformed(evt);
            }
        });

        btnComprobante.setToolTipText("Subir el comprobante de domicilio del adoptante");
        btnComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobanteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Correo:");

        txtCelular.setToolTipText("Número de teléfono celular del adoptante");

        jLabel14.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Folio:");

        txtFolio.setToolTipText("Folio de adopción");

        txtTelefonoR.setToolTipText("Teléfono de referencia (Fijo o móvil)");

        jLabel18.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Teléfono de referencia:");

        lblFecha.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha:");

        txtFecha.setToolTipText("Fecha de adopción");
        txtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaMouseClicked(evt);
            }
        });
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
        });

        txtNombre.setToolTipText("Nombre completo del adoptante");

        txtEdad.setToolTipText("Edad del adoptante");

        jLabel5.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad:");

        txtOcupacion.setToolTipText("Ocupación del adoptante");

        jLabel6.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ocupación:");

        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtDireccion.setToolTipText("Dirección del adoptante (Calle y número)");

        jLabel7.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dirección:");

        txtColonia.setToolTipText("Colonia del adoptante");

        jLabel8.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Colonia:");

        txtMunicipio.setToolTipText("Municipio del adoptante");

        jLabel11.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Celular:");

        txtTFFijo.setToolTipText("Número de telefono fijo del adoptante");
        txtTFFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTFFijoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de la persona:");

        jLabel12.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Teléfono fijo:");

        txtNombreR.setToolTipText("Nombre de referencia");

        jLabel13.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre de referencia:");

        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Municipio:");

        txtCorreo.setToolTipText("Dirección de correco electrónico del adoptante");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInfoAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(lblFecha)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(txtFecha)
                    .addComponent(txtNombre)
                    .addComponent(txtEdad)
                    .addComponent(txtOcupacion)
                    .addComponent(txtDireccion)
                    .addComponent(txtColonia)
                    .addComponent(txtMunicipio)
                    .addComponent(txtCorreo))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTFFijo, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(txtNombreR)
                                    .addComponent(txtFolio)
                                    .addComponent(txtTelefonoR)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnComprobante)
                                    .addComponent(btnCredencial))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInfoAnimal))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFecha)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAceptar)
                                    .addComponent(btnCancelar)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(txtColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTFFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefonoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel15)
                                    .addComponent(btnCredencial))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel17)
                                    .addComponent(btnComprobante))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {            
             btnAceptar.doClick();
        }
    }//GEN-LAST:event_formKeyPressed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        boolean comp = true;
        if (validarCajas().equals("true")) {
            if (JOptionPane.showConfirmDialog(this, "¿Seguro que quiere adoptar a " + lblNombre.getText() + "?") == 0) {
                adoptar.setAnimal_idAnimal(getId());
                adoptar.setCelular(txtCelular.getText());
                adoptar.setColonia(txtColonia.getText());
                adoptar.setComprobanteDomicilio(this.rutaComprobante);
                adoptar.setCorreo(txtCorreo.getText());
                adoptar.setCredencial(this.rutaCredencial);
                adoptar.setDireccion(txtDireccion.getText());
                adoptar.setEdad(Integer.parseInt(txtEdad.getText()));
                adoptar.setFolio(Integer.parseInt(txtFolio.getText()));
                adoptar.setMunicipio(txtMunicipio.getText());
                adoptar.setNombre(txtNombre.getText());
                adoptar.setNombreReferencia(txtNombreR.getText());
                adoptar.setOcupacion(txtOcupacion.getText());
                adoptar.setTelefonoFijo(txtTFFijo.getText());
                adoptar.setTelefonoReferencia(txtTelefonoR.getText());
                adoptar.setTipoComprobante(this.tipoCo);
                adoptar.setTipoCredencial(this.tipoCe);
                if (getLocalizacion().equals("Albergue temporal")) {
                    comp = temporal.eliminar(getId()).equals("Animal borrado");
                }
                if (adoptar.agregar().startsWith("Se agrego") && animal.enviarA(getId(), "Adoptados", validar.getFecha()).startsWith("Se envio") && comp) {
                    validar.agregarRecordatorio(lblNombre.getText(), "Adoptados");
                    JOptionPane.showMessageDialog(this, "Se han guardado los cambios");
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar los cambios");
                }
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, validarCajas());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtTFFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTFFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTFFijoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFechaKeyPressed

    private void txtFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFechaMouseClicked

    private void btnComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobanteActionPerformed
        // TODO add your handling code here:
        File archivo;
        this.selector.setFileFilter(this.filtro);
        int respuesta = this.selector.showOpenDialog(this);
        archivo = this.selector.getSelectedFile();
        if (archivo == null || archivo.getName().trim().equals("") || archivo.length() > 1048576) {
            JOptionPane.showMessageDialog(this, "Olvidaste subir un comprobante","Archivo incorrecto, el archivo es demaciado pesado, máximo 1024 KB", JOptionPane.ERROR_MESSAGE);
        } else {
            this.rutaComprobante = archivo.getAbsolutePath();
            try {
                this.tipoCo = Files.probeContentType(archivo.toPath());
            } catch (IOException ex) {
                System.out.println("Error en jifAgregarAdopcion.btnCredencial:\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnComprobanteActionPerformed

    private void btnCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCredencialActionPerformed
        // TODO add your handling code here:
        File archivo;
        this.selector.setFileFilter(this.filtro);
        int respuesta = this.selector.showOpenDialog(this);
        archivo = this.selector.getSelectedFile();
        if (archivo == null || archivo.getName().trim().equals("") || archivo.length() > 1048576) {
            JOptionPane.showMessageDialog(this, "Olvidaste subir una credencial","Archivo incorrecto, el archivo es demaciado pesado, máximo 1024 KB", JOptionPane.ERROR_MESSAGE);
        } else {
            this.rutaCredencial = archivo.getAbsolutePath();
            try {
                this.tipoCe = Files.probeContentType(archivo.toPath());
            } catch (IOException ex) {
                System.out.println("Error en jifAgregarAdopcion.btnCredencial:\n" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnCredencialActionPerformed

    private void btnInfoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoAnimalActionPerformed
        // TODO add your handling code here:
        info = new jifInformacionAn(getId());
        JDesktopPane desktopPane = this.getDesktopPane();
        desktopPane.add(info);
        info.setVisible(true);
    }//GEN-LAST:event_btnInfoAnimalActionPerformed

    private void lblFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFotoMouseClicked
        // TODO add your handling code here:
        verFoto = new jifVerImagen(getFoto(), lblNombre.getText());
        JDesktopPane desktopPane = this.getDesktopPane();
        desktopPane.add(verFoto);
        verFoto.setVisible(true);
    }//GEN-LAST:event_lblFotoMouseClicked
        
    private void myInitComponents() {
        Image imgCancelar = new ImageIcon("src/iconos/cruss.png").getImage();
        ImageIcon iconoCancelar = new ImageIcon(imgCancelar.getScaledInstance(32, 32, Image.SCALE_SMOOTH));
        btnCancelar.setIcon(iconoCancelar);    
        btnCancelar.setSize(32, 32);
        
        Image imgGaleria = new ImageIcon("src/iconos/camera.png").getImage();
        ImageIcon iconoGaleria = new ImageIcon(imgGaleria.getScaledInstance(150, 150, Image.SCALE_SMOOTH));
        lblFoto.setIcon(iconoGaleria);  
               
        Image imgAceptar = new ImageIcon("src/iconos/check.png").getImage();
        ImageIcon iconoAceptar = new ImageIcon(imgAceptar.getScaledInstance(32, 32, Image.SCALE_SMOOTH));
        btnAceptar.setIcon(iconoAceptar);
        
        Image imgCredencial = new ImageIcon("src/iconos/Subir archivo.png").getImage();
        ImageIcon iconoCredencial = new ImageIcon(imgCredencial.getScaledInstance(32, 32, Image.SCALE_SMOOTH));
        btnCredencial.setIcon(iconoCredencial);
        
        Image imgComprobante = new ImageIcon("src/iconos/Subir archivo.png").getImage();
        ImageIcon iconoComprobante = new ImageIcon(imgComprobante.getScaledInstance(32, 32, Image.SCALE_SMOOTH));
        btnComprobante.setIcon(iconoComprobante);
        
        try {
            rs = animal.consultarId(getId());
            if (rs.next()) {
                Blob blob = rs.getBlob("foto");
                ImageIcon icon;
                if (blob == null) {
                    Image img = new ImageIcon("src/iconos/gallery.png").getImage();
                    icon = new ImageIcon(img.getScaledInstance(150, 200, Image.SCALE_SMOOTH));
                } else {
                    byte[] data = blob.getBytes(1, (int) blob.length());
                    blob.free();
                    BufferedImage img = ImageIO.read(new ByteArrayInputStream(data));
                    setFoto(img);
                    icon = new ImageIcon(img.getScaledInstance(150, 200, Image.SCALE_SMOOTH));
                }
                lblFoto.setIcon(icon);
                setTitle("Adoptar - " + rs.getString("nombre"));
                lblNombre.setText(rs.getString("nombre"));
            }
        } catch (SQLException | IOException ex) {
            System.out.println("Error en jifAgregarAdopcion.myInitComponents():\n" + ex.getMessage());
        }
    }
    
    private String validarCajas() {
        String resultado = "true";
        if (rutaComprobante == null) {
            resultado = "Sube un comprobante";
            btnComprobante.requestFocus();
        }
        if (rutaCredencial == null) {
            resultado = "Sube una credencial";
            btnCredencial.requestFocus();
        }
        if (!validar.noVacio(txtFolio.getText())) {
            resultado = "Faltan datos";
            txtFolio.requestFocus();
        } else if (!validar.isNumber(txtFolio.getText())){
            resultado = "El folio debe ser un número";
            txtFolio.requestFocus();
        } 
        if (!(txtTelefonoR.getText().length() == 10 || txtTelefonoR.getText().length() == 7)) {
            resultado = "Debe ingresar un telefono fijo o celular, no ingreses carácteres entre los números";
            txtTelefonoR.requestFocus();
        }  
        if (!validar.noVacio(txtNombreR.getText())) {
            resultado = "Faltan datos";
            txtNombreR.requestFocus();
        } else if (txtNombreR.getText().length() > 100) {
            resultado = "El nombre de referencia es demaciado largo (máximo 100 carácteres";
        }
        if (txtTFFijo.getText().length() != 7) {
            resultado = "Debe ingresar un telefono fijo, no ingreses carácteres entre los números";
            txtTFFijo.requestFocus();
        }   
        if (txtCelular.getText().length() != 10) {
            resultado = "Debe ingresar un telefono celular, no ingreses carácteres entre los números";
            txtCelular.requestFocus();
        }   
        if (!validar.isEmail(txtCorreo.getText())) {
            resultado = "Ingresa un correo electrónico";
            txtCorreo.requestFocus();
        }
        if (!validar.noVacio(txtMunicipio.getText())) {
            resultado = "Faltan datos";
            txtMunicipio.requestFocus();
        } else if (txtMunicipio.getText().length() > 100) {
            resultado = "El municipio es demaciado largo (máximo 100 carácteres";
        }
        if (!validar.noVacio(txtColonia.getText())) {
            resultado = "Faltan datos";
            txtColonia.requestFocus();
        } else if (txtColonia.getText().length() > 100) {
            resultado = "La colonia es demaciado larga (máximo 100 carácteres";
        }
        if (!validar.noVacio(txtDireccion.getText())) {
            resultado = "Faltan datos";
            txtDireccion.requestFocus();
        } else if (txtDireccion.getText().length() > 100) {
            resultado = "La dirección es demaciado larga (máximo 100 carácteres";
        }
        if (!validar.noVacio(txtOcupacion.getText())) {
            resultado = "Faltan datos";
            txtOcupacion.requestFocus();
        } else if (txtOcupacion.getText().length() > 100) {
            resultado = "La ocupación es demaciado larga (máximo 100 carácteres";
        }
        if (!validar.noVacio(txtEdad.getText())) {
            resultado = "Faltan datos";
            txtEdad.requestFocus();
        } else if (!validar.isNumber(txtEdad.getText())){
            resultado = "La edad debe ser un número";
            txtEdad.requestFocus();
        }
        if (!validar.noVacio(txtNombre.getText())) {
            resultado = "Faltan datos";
            txtNombre.requestFocus();
        } else if (txtNombre.getText().length() > 100) {
            resultado = "El nombre es demaciado largo (máximo 100 carácteres";
        }
        if (!validar.esFecha(txtFecha.getText()).equals("true")){
            resultado = validar.esFecha(txtFecha.getText());
            txtFecha.requestFocus();
        }
        
        return resultado;
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComprobante;
    private javax.swing.JButton btnCredencial;
    private javax.swing.JButton btnInfoAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreR;
    private javax.swing.JTextField txtOcupacion;
    private javax.swing.JTextField txtTFFijo;
    private javax.swing.JTextField txtTelefonoR;
    // End of variables declaration//GEN-END:variables
}
