/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import huellitas.Administradores;
import huellitas.Validaciones;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class jifConfigurar extends javax.swing.JInternalFrame {
    private Validaciones validar = new Validaciones();
    private Administradores admin = new Administradores();
    
    private String sesionIniciada;

    public String getSesionIniciada() {
        return sesionIniciada;
    }

    public void setSesionIniciada(String sesionIniciada) {
        this.sesionIniciada = sesionIniciada;
    }
    
    /**
     * Creates new form jifConfigurar
     */
    public jifConfigurar(String sesionIniciada) {
        this.sesionIniciada = sesionIniciada;
        initComponents();
        
        Image imgCancelar = new ImageIcon("src/iconos/cruss.png").getImage();
        ImageIcon iconoCancelar = new ImageIcon(imgCancelar.getScaledInstance(32, 32, Image.SCALE_SMOOTH));
        btnCancelar.setIcon(iconoCancelar);        
        
        Image imgAceptar = new ImageIcon("src/iconos/check.png").getImage();
        ImageIcon iconoAceptar = new ImageIcon(imgAceptar.getScaledInstance(32, 32, Image.SCALE_SMOOTH));
        btnAceptar.setIcon(iconoAceptar);
        
        txtUsuario.setText(getSesionIniciada());
        txtUsuario.setEnabled(false);
        
        txtUsuario.setToolTipText("Si quieres cambiar tu nombre de usuario marca la casilla");
        txtActual.setToolTipText("Ingresa tu contraseña actual");
        txtPassword.setToolTipText("Ingresa tu nueva contraseña, no se permiten \"ñ\" ni símbolos");
        txtConfirmar.setToolTipText("Confirma tu nueva contraseña");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        lblContraseñaActual = new javax.swing.JLabel();
        lblContraseñaNueva = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtActual = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmar = new javax.swing.JPasswordField();
        cbxCambiar = new javax.swing.JCheckBox();

        setClosable(true);
        setTitle("Configuración");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/settings.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        txtUsuario.setToolTipText("Si quieres cambiar tu nombre de usuario selecciona la casilla a la izquierda");

        lblContraseñaActual.setBackground(new java.awt.Color(255, 255, 255));
        lblContraseñaActual.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        lblContraseñaActual.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseñaActual.setText("Contraseña actual:");

        lblContraseñaNueva.setBackground(new java.awt.Color(255, 255, 255));
        lblContraseñaNueva.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        lblContraseñaNueva.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseñaNueva.setText("Nueva contraseña:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirmar contraseña:");

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Amatic SC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONFIGURACIÓN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        btnAceptar.setMnemonic('g');
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setMnemonic('c');
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtActual.setToolTipText("Ingresa tu contraseña actual");

        txtPassword.setToolTipText("Ingresa una nueva contraseña, no puede contener símbolos ni \"ñ\"");

        txtConfirmar.setToolTipText("Vuelve a escribir tu contraseña nueva");

        cbxCambiar.setBackground(new java.awt.Color(0, 0, 0));
        cbxCambiar.setFont(new java.awt.Font("Patrick Hand SC", 0, 14)); // NOI18N
        cbxCambiar.setForeground(new java.awt.Color(255, 255, 255));
        cbxCambiar.setText("Cambiar nombre de usuario");
        cbxCambiar.setToolTipText("Selecciona si quieres cambiar tu nombre de usuario");
        cbxCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCambiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblContraseñaNueva)
                            .addComponent(lblContraseñaActual)
                            .addComponent(jLabel3)
                            .addComponent(cbxCambiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtActual)
                            .addComponent(txtPassword)
                            .addComponent(txtConfirmar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCambiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseñaActual)
                    .addComponent(txtActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseñaNueva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        
        if (validarCajas().equals("true")) {
            admin.setNombre(txtUsuario.getText());
            admin.setPassword(txtPassword.getText());

            if (admin.modificar(getSesionIniciada()).startsWith("Se modifico:")) {
                JOptionPane.showMessageDialog(this, "Se han guardado los cambios");
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al intentar guardar los cambios");
            }
        } else {
            JOptionPane.showMessageDialog(this, validarCajas());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cbxCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCambiarActionPerformed
        // TODO add your handling code here:
        txtUsuario.setText(getSesionIniciada());
        txtUsuario.setEnabled(cbxCambiar.isSelected());
    }//GEN-LAST:event_cbxCambiarActionPerformed

    public String validarCajas() {
        String resultado = "true";
        
        if (validar.noVacio(txtPassword.getText()) && validar.noVacio(txtConfirmar.getText()) && !txtPassword.getText().equals(txtConfirmar.getText())) {
            resultado = "Las contraseñas no coinciden";
            txtConfirmar.requestFocus();
        }
        
        if (!validar.noVacio(txtConfirmar.getText())) {
            resultado = "Confirma tu nueva contraseña";
            txtConfirmar.requestFocus();
        } 
        
        if (validar.noVacio(txtPassword.getText())) {
            if (!validar.isPassword(txtPassword.getText()).equals("true")) {
                resultado = validar.isPassword(txtPassword.getText());
                txtPassword.requestFocus();
            }
        } else {
            resultado = "Ingresa una nueva contraseña";
            txtPassword.requestFocus();
        }
        
        if (validar.noVacio(txtActual.getText())) {
            if (!admin.login(getSesionIniciada(), txtActual.getText()).equals("true")) {
                resultado = "Contraseña incorrecta";
                txtActual.requestFocus();
            }
        } else {
            resultado = "Ingresa tu contraseña actual";
            txtActual.requestFocus();
        }
        
        if (validar.noVacio(txtUsuario.getText())) {
            if (validar.isPassword(txtUsuario.getText()).equals("true")) {
                if (cbxCambiar.isSelected()) {
                    if (admin.usuarioExiste(txtUsuario.getText())) {
                        resultado = "Ya hay un usuario con ese nombre";
                        txtUsuario.requestFocus();
                    }
                }                
            } else {
                resultado = validar.isPassword(txtUsuario.getText());
                txtUsuario.requestFocus();
            }
        } else {
            resultado = "Ingresa un nombre de usuario";
            txtUsuario.requestFocus();
        }
        
        return resultado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox cbxCambiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblContraseñaActual;
    private javax.swing.JLabel lblContraseñaNueva;
    private javax.swing.JPasswordField txtActual;
    private javax.swing.JPasswordField txtConfirmar;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
